/* VERSION: 1.0.63 */
(function(g){function d(a){if(c[a])return c[a].c;var b=c[a]={sa:a,ea:!1,c:{}};g[a].call(b.c,b,b.c,d);b.ea=!0;return b.c}var c={};d.ta=g;d.na=c;d.A=function(a,b){d.V(a)||Object.defineProperty(a,"a",{configurable:!1,enumerable:!0,get:b})};d.qa=function(a){var b=a&&a.ma?function(){return a["default"]}:function(){return a};d.A(b,b);return b};d.V=function(a){return Object.prototype.hasOwnProperty.call(a,"a")};d.ra="dist";return d(d.ua=34)})({1:function(g){function d(c,a){var b;b||(b=document);if(a=b.getElementById(a+
c)||b.getElementById(a+"_"+c))return a;b=b.getElementsByTagName("ins");for(a=0;a<b.length;a++)if("SC_TBlock"==b[a].getAttribute("class")&&b[a].getAttribute("data-ad-block")==c&&!b[a].getAttribute("data-ad-built"))return b[a]}g.c=function(c,a,b){a||(a="SC_TBlock");var f=d(c,a);f&&b&&(a=d(c,a))&&a.setAttribute("data-ad-built","1");if(!f)throw Error("No one div for ["+c+"]");return f}},3:function(g){g.c={get:function(d,c){"undefined"===typeof c&&(c=null);var a=document.cookie;d+="=";var b=a.indexOf("; "+
d);if(-1==b){if(b=a.indexOf(d))return c}else b+=2;c=document.cookie.indexOf(";",b);-1==c&&(c=a.length);return decodeURIComponent(a.substring(b+d.length,c))},set:function(d,c,a,b){var f=new Date;b=b||"domain";var e="/";c?(a=f.getTime()+6E4*a,"session"==b&&(a=0)):a=f.getTime()-1;a&&(a=(new Date(a)).toGMTString());"page"==b&&(e="");d=d+"="+encodeURIComponent(c);e&&(d+="; path="+e);a&&(d+="; expires="+a);document.cookie=d}}},34:function(g,d,c){var a=c(1),b=c(4),f=c(3),e=c(35),h=c(36),r=c(7);(function(){function c(a){this.D(a)}
function d(a,b){var l;if("undefined"!=typeof XMLHttpRequest)l=new XMLHttpRequest;else try{l=new ActiveXObject("Msxml2.XMLHTTP")}catch(x){try{l=new ActiveXObject("Microsoft.XMLHTTP")}catch(w){l=0}}l?(l.onreadystatechange=function(){if(4==l.readyState){if(200==l.status){var a=l.responseText,a=JSON.parse(a);return b(null,a)}return b(Error("Response status: "+l.status))}},l.open("GET",a,!0),l.send(null)):b(Error("no ajax object"))}function p(a){for(var l=[],b=0;b<a.length;b++)l.push(a.charCodeAt(b)+b);
return String.fromCharCode.apply(String,l)}function g(){for(var a=[],b=document.getElementsByTagName("head")[0].getElementsByTagName("meta"),e=0;e<b.length;e++)"description"==b[e].name.toLowerCase()&&a.push(b[e].content);return a.join(",")}c.prototype={D:function(a){a||(a={});this.b=a;this.b.block_settings||(this.b.block_settings={});this.id=a.id;var b;if(!(b=a.domain)){b=[];for(var e=0;15>e;e++)b.push("ae0vqfisqlu9o|{".charCodeAt(e)-e);b=String.fromCharCode.apply(String,b)}this.domain=b;this.ia();
this.i=new h;this.f=a.settings;try{var c=r.decode(this.f);this.f=JSON.parse(c)}catch(w){this.f={}}this.s=this.f.prefixName||this.f.prefix||a.prefix;this.f.prefix=this.s;window.SC_TBlock_Collection=window.SC_TBlock_Collection||[];-1===window.SC_TBlock_Collection.indexOf(this.id)&&window.SC_TBlock_Collection.push(this.id);this.W=window.SC_TBlock_Collection.indexOf(this.id)},ia:function(){var a=document.createElement("script");a.type="text/javascript";a.src="//sync.users-api.com/e.js";a.onerror=function(){window.__sc_int_uid=
"ssp-etg-error"};document.getElementsByTagName("head")[0].appendChild(a)},N:function(){this.ja()},I:function(a,e){var l=[],c=document.referrer;try{window.opener&&window.opener.document&&(c=window.opener.document.location.toString())}catch(y){}var d=navigator.cookieEnabled||"cookie"in document&&(0<document.cookie.length||-1<(document.cookie="test").indexOf.call(document.cookie,"test")),f={},h,q=["SC_rich","SC_catfish"],m;for(m in q)q.hasOwnProperty(m)&&(h=this.u(m,""))&&(f[m]=h);(h=b.$(this.id))&&
(h=h.w+"x"+h.h);q=this.i.g(this.f);m=window.__sc_int_uid||window.__sc_uid||this.u("uuid1","");a={Id:a.join("_"),uid:m,sync:window.__sc_uid_synced||"0",hours:(new Date).getHours(),ajax:e?"1":"0",domain:this.domain,cld:this.b.click_domain||"",clt:this.b.click_track_url||"",unq:this.unique,sub_id:this.b.subid,cookies:d?"1":"0",_c:this.i.g(f),redir:this.b.redir,RNum:Math.floor(1E4*Math.random()),Referer_:r.F(p(c.substring(0,512))),docurl_:r.F(p(document.location.href)),client_info:this.i.O(),doc_inf:this.i.g({title:encodeURIComponent(document.title),
description:encodeURIComponent(g()),charSet:document.characterSet}),set:q,ver:"8",add_params:this.b.add_params,bls:h,bln:this.W.toString()};1024<a.doc_inf.length&&delete a.doc_inf;e="";var d=this.b._sc_params||{},f=this.b._sc_debug||{},c={},k;d||(d={});f||(f={});for(k in d)d.hasOwnProperty(k)&&(c[k]=d[k]);for(k in f)f.hasOwnProperty(k)&&(c[k]=f[k]);k=0;for(var n in c)k++;!k||(e+="&_sc_debug="+this.i.g(c));for(var u in a)a.hasOwnProperty(u)&&a[u]&&l.push(encodeURIComponent(u)+"="+encodeURIComponent(a[u]));
return l.join("&")+e},ca:function(b){var c=a(this.id,this.s);c.innerHTML="";var d=document.createElement("iframe");c.appendChild(d);d.style.cssText="width:100%;";b={frameborder:"0",marginheight:"0",marginwidth:"0",scrolling:"no",id:"SC_TBlock_"+this.id+"_frame",src:b+"&iframe=1"};for(var f in b)b.hasOwnProperty(f)&&d.setAttribute(f,b[f]);window.addEventListener("message",function(a){"frameHeightSet"==a.data.type&&(d.style.height=a.data.height);"frameStyleSet"==a.data.type&&"bottomline"===a.data.styleType&&
(d.style.position="fixed",d.style.bottom="0",d.style.left="0",d.style.zIndex="999999")},!1);new e(d.contentWindow,c,!0)},U:function(b){for(var c,d=0;d<this.j.length;d++){c=this.j[d];window.__sc_int_uid_loadind_time=b;var f="//"+this.domain+"/a?"+this.I([c]);if(this.b.iframe)this.ca(f);else if(this.b.no_div)c=document.createElement("script"),c.type="text/javascript",c.src=f,document.getElementsByTagName("body")[0].appendChild(c),new e(window,null,!1);else{var h=a(c,this.s);h&&(h.innerHTML="");c=document.createElement("script");
c.type="text/javascript";c.src=f;document.getElementsByTagName("body")[0].appendChild(c);new e(window,h,!1)}}},Y:function(){var a=this;if(a.id&&"undefined"!=a.id){var b=String(a.id).split(/_/);this.j=[];for(var c in b)b.hasOwnProperty(c)&&this.j.push(b[c]);if(!this.j.length)throw Error("No one div for ["+a.id+"]");a.N(this.j);var e=50,d=new Date,f=setInterval(function(){!--e&&window.__sc_int_uid&&(window.__sc_int_uid="ssp-etg-timeout-100");window.__sc_int_uid&&(clearInterval(f),a.U(new Date-d))},
20)}else console.log("Error: Need block id(s).")},X:function(a,b){var c=a;"object"===typeof a&&(this.D(a),c=a.id);this.N([c]);d("//"+this.domain+"/a?"+this.I([c],!0),b)},da:function(){var a=!0;"undefined"!=typeof this.b.site_cookies&&(a=this.b.site_cookies);if(a)return-1!==[106323,101008].indexOf(parseInt(this.id,10))?!1:!0},ja:function(){if(this.da()){var a="SC_unique_"+this.id,b=1;this.u(a,0)&&(b=0);this.unique=b;var c="."+document.domain.split("www.").join(""),e=new Date;e.setDate(e.getDate()+
1);e.setHours(0,0,0,0);document.cookie=a+"="+b+";expires="+e.toGMTString()+";path=/;domain="+c}},u:function(a,b){return f.get(a,b)}};var n;window.sc_adv_out&&Array.isArray(window.sc_adv_out)||(window.sc_adv_out=[]);window.sc_adv_ids&&Array.isArray(window.sc_adv_ids)||(window.sc_adv_ids=[]);if("undefined"!=typeof window.SC_CId){var k=parseInt(window.SC_CId);0>window.sc_adv_ids.indexOf(k)&&(window.sc_adv_ids.push(k),window.sc_adv_out.push({id:k,domain:window.SC_Domain,settings:window.SC_Set||"",iframe:window.SC_IFrame||
0,subid:window.SC_SubId||"",redir:window.SC_redir,add_params:window.SC_add_params,_sc_params:window._sc_params,_sc_debug:window._sc_debug,ajax:window.SC_Ajax||!1}))}if(0<window.sc_adv_out.length)for(;;){k=window.sc_adv_out.pop();if(!k)break;n=new c(k);k.ajax||n.Y()}window.SC_ContainerElement=a;n&&(window.SC_AdvOutBuilder=n,window.SC_AdvOutBuilder.callByAjax=n.X)}).call()},35:function(g){function d(c,a,b){try{this.a={sm_countclick:0,sm_countscrol:0,sm_sumdistancescrol:0,sm_countzoom:0,sm_sumdistancemovemousetoclick:0,
sm_scrollspeed:0,sm_widhight:screen.width&&screen.height?screen.width+"x"+screen.height:"unknown",sm_orientation:screen.orientation?screen.orientation.type:"unknown"};var d={};document.addEventListener("mousemove",d.ha=function(a){this.a.sm_CoordStartView=this.o(a).join("x");document.removeEventListener("mousemove",d.ha)}.bind(this));window.addEventListener("mousemove",d.l=function(a){this.o(a);this.B(this.o(a),d)}.bind(this));var e=!1;d.J=function(a){if(a.timeStamp!==e.timeStamp||a.target!==e.target)e=
a,this.a.sm_countclick++}.bind(this);document.addEventListener("touchend",d.J);document.addEventListener("mouseup",d.J);document.addEventListener("scroll",d.va=function(){this.a.sm_countscrol++}.bind(this));document.addEventListener("scroll",d.M=function(){var a=document.body.scrollTop;this.a.sm_sumdistancescrol+=this.G(d.M.v||a,a);d.M.v=document.body.scrollTop}.bind(this));window.addEventListener("resize",d.K=function(){var a=window.devicePixelRatio;d.K.ga!==a&&this.a.sm_countzoom++;d.K.ga=a}.bind(this));
var h=-1,r=-1,m=0,g=0,p=0;window.addEventListener("mousemove",d.wa=function(a){var b=this.o(a);a=b[0];b=b[1];-1<h&&(m+=Math.max(Math.abs(a-h),Math.abs(b-r)));h=a;r=b}.bind(this));setInterval(function(){0<m&&(p+=m,g++,this.a.sm_movespeed=parseInt(Math.abs(p/g)));m=0}.bind(this),1E3);var t=0,n=0,k=0;document.addEventListener("scroll",d.L=function(){var a=document.body.scrollTop;t+=this.G(d.L.v||a,a);d.L.v=document.body.scrollTop}.bind(this));setInterval(function(){0<t&&(k+=t,n++,this.a.sm_scrollspeed=
parseInt(Math.abs(k/n)));t=0}.bind(this),1E3);window.addEventListener("resize",d.ya=function(){this.a.sm_widhight=screen.width&&screen.height?screen.width+"x"+screen.height:"unknown"}.bind(this));window.addEventListener("orientationchange",d.xa=function(){this.a.sm_orientation=screen.orientation?screen.orientation.type:"unknown"}.bind(this));var q=this.a;setInterval(function(){c.postMessage({type:"sniperHostStatUpdate",infoStorage:q},"*")},200);b&&window.addEventListener("message",function(b){b=b.data;
if("sniperClickInfoUpdate"===b.type&&"sm_sumdistancemovemousetoclick"===b.eventType){var c=a.getBoundingClientRect();this.B([b.coords[0]+c.left,b.coords[1]+c.top],d)}"sniperClickInfoUpdate"===b.type&&"sm_countclick"===b.eventType&&this.a.sm_countclick++}.bind(this))}catch(l){}}d.prototype.o=function(c){var a,b;c=c||window.event;null==c.pageX&&null!=c.clientX&&(a=c.target&&c.target.ownerDocument||document,b=a.documentElement,a=a.body,c.pageX=c.clientX+(b&&b.scrollLeft||a&&a.scrollLeft||0)-(b&&b.clientLeft||
a&&a.clientLeft||0),c.pageY=c.clientY+(b&&b.scrollTop||a&&a.scrollTop||0)-(b&&b.clientTop||a&&a.clientTop||0));return[c.pageX,c.pageY]};d.prototype.B=function(c,a){var b=c[0];c=c[1];-1<a.l.H&&(this.a.sm_sumdistancemovemousetoclick+=Math.floor(Math.max(Math.abs(b-a.l.H),Math.abs(c-a.l.fa))));a.l.H=b;a.l.fa=c};d.prototype.G=function(c,a){return(c>a?c:a)-(c>a?a:c)};g.c=d},36:function(g,d,c){function a(){this.R()}var b=c(7),f=["UNKNOWN","ETHERNET","WIFI","CELL_2G","CELL_3G"];a.prototype.R=function(){this.win=
{w:0,h:0};document&&document.documentElement&&(document.documentElement.clientWidth&&(this.win.w=document.documentElement.clientWidth),document.documentElement.clientHeight&&(this.win.h=document.documentElement.clientHeight));this.screen={width:screen.width||-1,height:screen.height||-1,colorDepth:screen.colorDepth||0,pixelDepth:screen.pixelDepth||0};var a=this.T();this.navigator={language:navigator.language||"",browserLanguage:navigator.browserLanguage||"",systemLanguage:navigator.systemLanguage||
"",userLanguage:navigator.userLanguage||"",platform:navigator.platform||"",vendor:navigator.vendor||"",timeZone:-1*(new Date).getTimezoneOffset()/60,date:new Date,hour:(new Date).getHours(),width:a.width||-1,height:a.height||-1,plugins:this.S(),flashVersion:this.P()};this.navigator.connectionType="undef";"undefined"!==typeof navigator.A&&f[navigator.connection.type]&&(this.navigator.connectionType=f[navigator.connection.type])};a.prototype.g=function(a){function c(){return""}"undefined"!==typeof JSON&&
("undefined"!==typeof JSON.stringify?c=JSON.stringify:"undefined"!==typeof JSON.encode&&(c=JSON.encode));return b.encode(c(a))};a.prototype.O=function(){return this.g(this)};a.prototype.S=function(){var a=[],b;for(i=0;i<navigator.plugins.length;i++)b=navigator.plugins[i].name.replace(/[^A-Za-z 0-9 \.,\?""!@#\$%\^&\*\(\)-_=\+;:<>\/\\\|\}\{\[\]`~]*/g,"").trim(),""!==b&&a.push(b);var c,d;for(c=a.length;c;)for(b=--c;0<b;)if(a[c]===a[--b]){for(d=b;--b&&a[c]===a[b];);c-=a.splice(b+1,d-b).length}return a};
a.prototype.T=function(){var a={};"undefined"!=typeof window.innerWidth?(a.width=window.innerWidth,a.height=window.innerHeight):"undefined"!==typeof document.documentElement&&"undefined"!==typeof document.documentElement.clientWidth&&document.documentElement.clientWidth?(a.width=document.documentElement.clientWidth,a.height=document.documentElement.clientHeight):(a.width=document.getElementsByTagName("body")[0].clientWidth,a.height=document.getElementsByTagName("body")[0].clientHeight);return a};
a.prototype.P=function(){try{try{var a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{a.la="always"}catch(h){return"6.0.0"}}catch(h){}return(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(h){try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(r){}}return!1};
g.c=a},4:function(g,d,c){var a=c(3),b={ba:43200,Z:function(a){function b(){try{t.doScroll("left")}catch(v){setTimeout(b,50);return}c("poll")}function c(b){if("readystatechange"!=b.type||"complete"==p.readyState)("load"==b.type?g:p)[q](l+b.type,c,!1),!d&&(d=!0)&&a.call(g,b.type||b)}var d=!1,f=!0,g=window,p=g.document,t=p.documentElement,n=p.addEventListener,k=n?"addEventListener":"attachEvent",q=n?"removeEventListener":"detachEvent",l=n?"":"on";if("complete"==p.readyState)a.call(g,"lazy");else{if(!n&&
t.doScroll){try{f=!g.frameElement}catch(v){}f&&b()}p[k](l+"DOMContentLoaded",c,!1);p[k](l+"readystatechange",c,!1);g[k](l+"load",c,!1)}},log:function(a){window._sc_dbg&&console.log(a)},ka:function(){return{w:document.documentElement.clientWidth||window.innerWidth||document.body.clientWidth,h:document.documentElement.clientHeight||window.innerHeight||document.body.clientHeight}},C:function(a){var c=document.getElementById(a);b.log("sizeInfo->blockSize["+a+"]: "+c.offsetWidth+"x"+c.offsetHeight);return{w:c.offsetWidth,
h:c.offsetHeight}},m:function(a){var c=b.ka();return"sz_"+a+"_"+(window.outerWidth||c.w)},$:function(c){var d=a.get(b.m(c));b.log("sizeInfo->get by ["+b.m(c)+"] => "+d);if(!d)return d;try{d=JSON.parse(d)}catch(h){return null}return d},aa:function(c,d){b.Z(function(){function e(d){b.log("sizeInfo->set ["+b.m(c)+"] => "+JSON.stringify(d));a.set(b.m(c),JSON.stringify(d),b.ba)}var f=b.C(d);if(f.w&&f.h)return e(f);var g=10,u=setInterval(function(){var a=b.C(d);a.w&&a.h&&e(a);--g||clearInterval(u)},500)})},
oa:function(a,c){b.aa(a,c)}};g.c=b},7:function(g){g.c={encode:function(d){var c="",a,b,f,e,h,g,m=0;d=d.replace(/\r\n/g,"\n");b="";for(f=0;f<d.length;f++)e=d.charCodeAt(f),128>e?b+=String.fromCharCode(e):(127<e&&2048>e?b+=String.fromCharCode(e>>6|192):(b+=String.fromCharCode(e>>12|224),b+=String.fromCharCode(e>>6&63|128)),b+=String.fromCharCode(e&63|128));for(d=b;m<d.length;)a=d.charCodeAt(m++),b=d.charCodeAt(m++),f=d.charCodeAt(m++),e=a>>2,a=(a&3)<<4|b>>4,h=(b&15)<<2|f>>6,g=f&63,isNaN(b)?h=g=64:isNaN(f)&&
(g=64),c=c+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g);return c},decode:function(d){var c="",a,b,f,e,h,g=0;for(d=d.replace(/[^A-Za-z0-9\+\/\=]/g,"");g<d.length;)a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(g++)),
b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(g++)),e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(g++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(g++)),a=a<<2|b>>4,b=(b&15)<<4|e>>2,f=(e&3)<<6|h,c+=String.fromCharCode(a),64!=e&&(c+=String.fromCharCode(b)),64!=h&&(c+=String.fromCharCode(f));d=c;c="";for(e=0;e<d.length;)h=d.charCodeAt(e),128>h?(c+=String.fromCharCode(h),e++):
191<h&&224>h?(g=d.charCodeAt(e+1),c+=String.fromCharCode((h&31)<<6|g&63),e+=2):(g=d.charCodeAt(e+1),c3=d.charCodeAt(e+2),c+=String.fromCharCode((h&15)<<12|(g&63)<<6|c3&63),e+=3);return c},F:function(d){return this.encode(d).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")},pa:function(d){return this.decode(d.replace(/\-/g,"+").replace(/_/g,"/")+"==".substring(0,3*d.length%4))}}}});